# golangci-lint v2 設定ファイル
# 2024-2025年のGoベストプラクティスに準拠

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # メタリンター（推奨）
    - staticcheck  # 最新のGoベストプラクティス検出

    # 基本リンター
    - errcheck     # エラーチェック漏れ検出
    - gosimple     # コード簡略化の提案
    - govet        # Go標準のvet
    - ineffassign  # 無駄な代入検出
    - unused       # 未使用コード検出

    # コード品質
    - gofmt        # フォーマットチェック
    - goimports    # import文の整理
    - revive       # golintの後継
    - misspell     # スペルミスチェック

    # パフォーマンス
    - prealloc     # スライスの事前割り当て提案

    # セキュリティ
    - gosec        # セキュリティ問題検出

  disable:
    - typecheck    # go buildでカバーされるため

linters-settings:
  staticcheck:
    checks:
      - all
      - "-SA1019"  # 非推奨API使用の警告を一時的に無効化（移行期間用）

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  gosec:
    excludes:
      - G404  # 暗号学的に安全でない乱数（教育目的のため許容）

  errcheck:
    check-blank: true
    check-type-assertions: true

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-rules:
    # テストファイルでの一般的なパターンを許容
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # 共通の誤検出を除外
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck

  max-issues-per-linter: 50
  max-same-issues: 3
  uniq-by-line: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
