# golangci-lint 設定ファイル
# 2024-2025年のGoベストプラクティスに準拠

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # 基本リンター
    - errcheck     # エラーチェック漏れ検出
    - govet        # Go標準のvet
    - staticcheck  # 最新のGoベストプラクティス検出
    - unused       # 未使用コード検出
    - ineffassign  # 無駄な代入検出

    # コード品質
    - revive       # golintの後継
    - misspell     # スペルミスチェック

    # セキュリティ
    - gosec        # セキュリティ問題検出

linters-settings:
  staticcheck:
    checks:
      - all
      - "-SA1019"  # 非推奨API使用の警告を一時的に無効化（移行期間用）

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  gosec:
    excludes:
      - G404  # 暗号学的に安全でない乱数（教育目的のため許容）
      - G304  # ファイル読み込み（教育目的のため許容）

  errcheck:
    check-blank: true
    check-type-assertions: true

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-rules:
    # テストファイルでの一般的なパターンを許容
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # 共通の誤検出を除外
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck

    # G304: ファイル読み込みの警告を除外（教育目的）
    - text: "G304"
      linters:
        - gosec

  max-issues-per-linter: 50
  max-same-issues: 3
  uniq-by-line: true

# output設定はデフォルトを使用
